#Use an existing docker image as  base

FROM node:alpine

WORKDIR '/app'

#Install some dependencies
COPY package.json .
RUN npm install
COPY . .



#Tell the image what to do when it starts as a container

CMD ["npm", "run", "start"]